APP_NAME = "OpenFix AI"
APP_VERSION = "0.5.2-dev12"

# Shared diagnostic thresholds. These are estimates, not hardware verdicts.
CPU_HIGH = 85
CPU_CRITICAL = 95
SLOW_CPU_HIGH = 80
SLOW_CPU_CRITICAL = 90
RAM_HIGH = 85
RAM_CRITICAL = 95
GPU_WARM_C = 83
GPU_HOT_C = 90
PACKET_LOSS_WARN = 3
PACKET_LOSS_HEAVY = 10
PING_GOOD_MS = 80
PING_HIGH_MS = 150

SCORE_HEALTHY = 90
SCORE_CHECK = 75
SCORE_ATTENTION = 50
RESOURCE_NORMAL_CPU_MAX = 70
RESOURCE_NORMAL_RAM_MAX = 80

# Storage thresholds are intentionally adaptive. Percentage alone is not enough
# for very large data drives, so both free GiB and percentage are considered.
SYSTEM_DISK_CRITICAL_GB = 5
SYSTEM_DISK_LOW_GB = 15
SYSTEM_DISK_CRITICAL_PERCENT = 3
SYSTEM_DISK_LOW_PERCENT = 8
SYSTEM_DISK_PERCENT_GB_CAP = 20
SYSTEM_DISK_LOW_PERCENT_GB_CAP = 30

DATA_DISK_CRITICAL_GB = 2
DATA_DISK_LOW_GB = 10
DATA_DISK_CRITICAL_PERCENT = 2
DATA_DISK_LOW_PERCENT = 5
DATA_DISK_PERCENT_GB_CAP = 10
DATA_DISK_LOW_PERCENT_GB_CAP = 25

EVENT_LOOKBACK_HOURS = 24
EVENT_MAX_EVENTS = 80

# Logging
LOG_MAX_BYTES = 2 * 1024 * 1024
LOG_BACKUP_COUNT = 3
